# Generated by Django 4.2.6 on 2023-10-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название поста', max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание урока')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('publication_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
