# Generated by Django 4.2.6 on 2023-10-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название работы')),
                ('main_image', models.ImageField(upload_to='', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Мои работы',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Работа без названия', max_length=100, verbose_name='Название работы')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение работы')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artworks', verbose_name='Какая работа')),
            ],
            options={
                'verbose_name': 'Изображение работы',
                'verbose_name_plural': 'Изображения работ',
            },
        ),
    ]
