# Generated by Django 4.2.6 on 2023-10-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworks',
            options={'verbose_name': 'проект', 'verbose_name_plural': 'Мои проекты'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'работу', 'verbose_name_plural': 'Работы'},
        ),
        migrations.AlterField(
            model_name='artworks',
            name='main_image',
            field=models.ImageField(upload_to='images', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='artworks',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='images',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artworks', verbose_name='Привязка к проекту'),
        ),
    ]
