# Generated by Django 4.2.6 on 2023-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_artworks_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworks',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Уникальное название'),
            preserve_default=False,
        ),
    ]
